### ISSUE TITLE
Need to improve the "Case Study" document

### ISSUE THREAD

**Issue by RobertLRead** [18F/consulting#1]
I just ripped it out of a larger document.

**Comment by blacktm** [comment]
@RobertLRead Which document is this?

**Comment by RobertLRead** [comment]
@blacktm dude, you broke the links --- it now needs to be /assets/docs/ for
the static links.

I have repaired it.

On Wed, Dec 10, 2014 at 5:57 PM, Tom Black notifications@github.com wrote:

> @RobertLRead https://github.com/RobertLRead Which document is this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/consulting/issues/1#issuecomment-66540479.

## 

Robert L. Read, PhD
Managing Director, 18F Consulting http://18f.github.io/consulting/
(202) 809-1941

**Comment by blacktm** [comment]
Whoops, those were suppose to be prefixed with `{{ site.baseurl }}/assets/docs/` so the links will work when served locally or on gh-pages. Fixed! Thanks for catching!
