### ISSUE TITLE
Change all AAA references to 18F Consulting Services

### ISSUE THREAD

**Issue by quepol** [18F/consulting#5]
- change all references to AAA or "Agile Assisted Acquisitions"
- change name of repo to `consulting` ??

**Comment by RobertLRead** [comment]
Yes, I will change the name of the repo.

On Tue, Oct 7, 2014 at 5:14 AM, Hillary Hartley notifications@github.com
wrote:

> - change all references to AAA or "Agile Assisted Acquisitions"
> - change name of repo to consulting ??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/aaa/issues/5.

## 

Robert L. Read, PhD
Co-Founder, 18F
(202) 809-1941
