### ISSUE TITLE
Welcome contributions from the public

### ISSUE THREAD

**Issue by cscairns** [18F/consulting#6]
Ref: 

"Unlike other repositories of 18F, this repo does not invite contributions from the public. However, all materials found here may be freely redistributed under the Creative Commons license."

**Comment by adelevie** [comment]
Also, a small point: the materials in the repo are in the public domain in the United States (and anywhere where the waiver of copyright in the license takes effect). Only elsewhere does the CC license apply. CC implies an assertion of copyright, which 18F does not do to the extent it is possible.

**Comment by blacktm** [comment]
Can we remove this text?

> "Unlike other repositories of 18F, this repo does not invite contributions from the public. However, all materials found here may be freely redistributed under the Creative Commons license."

This new template includes an "improve this content" link in the footer, which can be disabled if needed. As we write more content, I can see contributions being useful. Any thoughts?
